arch:
  value: 
    name: CAERNetS

dataset:
  value:
    name: CAERS
    args:
      root: /data/CAER-S_pre
      batch_size: 32
      num_workers: 16

loss:
  value: cross_entropy

optimizer:
  value:
    name: SGD
    args:
      lr: 5.0e-3
      momentum: 0.9
      nesterov: true
lr_scheduler:
  value:
    name: StepLR
    args:
      step_size: 160 # close to 150
      gamma: 0.1
metrics:
  value:
    - accuracy
    - top_k_acc
trainer:
  value:
    name: BaseCAERS
    seed: 0
    use_gpu: true
    gpu_ids: 0
    epochs: 150
    monitor: max val_accuracy
    early_stop: 20