arch:
  value: 
    name: EMOTIC

dataset:
  value:
    name: EMOTIC
    args:
      root: /data/emotic_pre
      batch_size: 52
      num_workers: 16

loss:
  value:
  - weighted_euclidean_loss
  - smooth_L1

optimizer:
  value:
    name: SGD
    args:
      lr: 5.0e-3
      momentum: 0.9
      nesterov: true
lr_scheduler:
  value:
    name: StepLR
    args:
      step_size: 60 # close to 50
      gamma: 0.1
metrics:
  value:
    - mean_ap
    - mean_aae
trainer:
  value:
    name: BaseEmotic
    seed: 0
    use_gpu: true
    gpu_ids: 0
    epochs: 50
    monitor: max val_mean_ap
    early_stop: 20